### ISSUE TITLE
Vapoursynth R58

### ISSUE THREAD

**Issue by Selur** [HolyWu/vs-dpir#22]
Trying to install vs-dpir to latest portable [Vapoursynth R58-RC1](https://github.com/vapoursynth/vapoursynth/releases/tag/R58-RC1),
but I get:
```
I:\Hybrid\64bit\Vapoursynth>python -m pip install --upgrade vsdpir
Collecting vsdpir
  Downloading vsdpir-2.1.0-py3-none-any.whl (7.0 kB)
Collecting VapourSynth>=55
  Downloading VapourSynth-57.zip (567 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 567.1/567.1 KB 7.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Selur\AppData\Local\Temp\pip-install-8umebnq_\vapoursynth_2f81ae9c21b34d768097c5a208b5989a\setup.py", line 64, in <module>
          dll_path = query(winreg.HKEY_LOCAL_MACHINE, REGISTRY_PATH, REGISTRY_KEY)
        File "C:\Users\Selur\AppData\Local\Temp\pip-install-8umebnq_\vapoursynth_2f81ae9c21b34d768097c5a208b5989a\setup.py", line 38, in query
          reg_key = winreg.OpenKey(hkey, path, 0, winreg.KEY_READ)
      FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Selur\AppData\Local\Temp\pip-install-8umebnq_\vapoursynth_2f81ae9c21b34d768097c5a208b5989a\setup.py", line 67, in <module>
          raise OSError("Couldn't detect vapoursynth installation path")
      OSError: Couldn't detect vapoursynth installation path
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
any idea how to get vs-dpir setup with Vapoursynth R58?

**Comment by HolyWu** [comment]
Unfortunately ONNX Runtime doesn't support Python 3.10 yet. Wait for its new version or use vs-mlrt.
