### ISSUE TITLE
Problem installing vs-dpir "cannot import name 'ccfDisableAutoLoading' "

### ISSUE THREAD

**Issue by Selur** [HolyWu/vs-dpir#41]
Hi, I'm having trouble installing the new vs-dpir with R68 (installing the old 3.1.1 version with older torch&co worked a few days ago)

What I did was
* create 'Vapoursynth'-folder
* downloaded 'Windows embeddable package (64-bit)' from https://www.python.org/downloads/release/python-3123/
* extracted it into the 'Vapoursynth'-folder
* downloaded 'VapourSynth64-Portable-R68' from https://github.com/vapoursynth/vapoursynth/releases
* extracted it into the 'Vapoursynth'-folder
* download get-pip.py from https://bootstrap.pypa.io/get-pip.py into the 'Vapoursynth'-folder
* ran `python get-pip.py`
* adjusted `python312._pth` by adding:
  ```
  Scripts
  Lib\site-packages
  ```
* called `python -m pip install wheel/VapourSynth-68-cp312-cp312-win_amd64.whl`
* downloaded https://github.com/HolyWu/vs-dpir/releases/download/v4.0.0/torch_tensorrt-2.4.0.dev0+8915f846d-cp312-cp312-win_amd64.whl
* called:
```
python -m pip install wheel
python -m pip install torch_tensorrt-2.4.0.dev0+8915f846d-cp312-cp312-win_amd64.whl
python -m pip install --pre torch-tensorrt --index-url https://download.pytorch.org/whl/nightly/cu121
```
* called `pip install -U vsdpir`
* called `python -m vsdpir` which gave me:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "F:\Vapoursynth\Lib\site-packages\vsdpir\__init__.py", line 12, in <module>
    from vstools import check_variable, fallback, vs
  File "F:\Vapoursynth\Lib\site-packages\vstools\__init__.py", line 5, in <module>
    from .utils import *  # noqa: F401, F403
    ^^^^^^^^^^^^^^^^^^^^
  File "F:\Vapoursynth\Lib\site-packages\vstools\utils\__init__.py", line 1, in <module>
    from . import vs_proxy as vapoursynth
  File "F:\Vapoursynth\Lib\site-packages\vstools\utils\vs_proxy.py", line 17, in <module>
    from vapoursynth import (
ImportError: cannot import name 'ccfDisableAutoLoading' from 'vapoursynth' (F:\Vapoursynth\Lib\site-packages\vapoursynth.cp312-win_amd64.pyd)
```
Not really much of a problem for me atm., since I'm stuck at R65, since I can't get BasicVSR++ working due to missing mmvc for Python 3.12. 
But I wanted to let you know that there might be a problem somewhere.

**Comment by HolyWu** [comment]
Ah. Currently need to install the latest git version of vs-tools until a new version is published.

```
pip install git+https://github.com/Jaded-Encoding-Thaumaturgy/vs-tools.git
```

**Comment by Selur** [comment]
Sadly, that did not solve the problem:
```
F:\Vapoursynth>python -m pip install git+https://github.com/Jaded-Encoding-Thaumaturgy/vs-tools.git
Collecting git+https://github.com/Jaded-Encoding-Thaumaturgy/vs-tools.git
  Cloning https://github.com/Jaded-Encoding-Thaumaturgy/vs-tools.git to c:\users\selur\appdata\local\temp\pip-req-build-2k6baxxc
  Running command git clone --filter=blob:none --quiet https://github.com/Jaded-Encoding-Thaumaturgy/vs-tools.git 'C:\Users\Selur\AppData\Local\Temp\pip-req-build-2k6baxxc'
  Resolved https://github.com/Jaded-Encoding-Thaumaturgy/vs-tools.git to commit 7bee1667f5f3daa84af72e3bb905617ea83fa864
  Preparing metadata (setup.py) ... done
Requirement already satisfied: VapourSynth>=65 in f:\vapoursynth\lib\site-packages (from vstools==3.1.0) (68)
Requirement already satisfied: stgpytools>=1.0.5 in f:\vapoursynth\lib\site-packages (from vstools==3.1.0) (1.0.5)
Requirement already satisfied: rich>=12.6.0 in f:\vapoursynth\lib\site-packages (from vstools==3.1.0) (13.7.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in f:\vapoursynth\lib\site-packages (from rich>=12.6.0->vstools==3.1.0) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in f:\vapoursynth\lib\site-packages (from rich>=12.6.0->vstools==3.1.0) (2.18.0)
Requirement already satisfied: mdurl~=0.1 in f:\vapoursynth\lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.6.0->vstools==3.1.0) (0.1.2)

F:\Vapoursynth>python -m vsdpir
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "F:\Vapoursynth\Lib\site-packages\vsdpir\__init__.py", line 12, in <module>
    from vstools import check_variable, fallback, vs
  File "F:\Vapoursynth\Lib\site-packages\vstools\__init__.py", line 5, in <module>
    from .utils import *  # noqa: F401, F403
    ^^^^^^^^^^^^^^^^^^^^
  File "F:\Vapoursynth\Lib\site-packages\vstools\utils\__init__.py", line 1, in <module>
    from . import vs_proxy as vapoursynth
  File "F:\Vapoursynth\Lib\site-packages\vstools\utils\vs_proxy.py", line 17, in <module>
    from vapoursynth import (
ImportError: cannot import name 'ccfDisableAutoLoading' from 'vapoursynth' (F:\Vapoursynth\Lib\site-packages\vapoursynth.cp312-win_amd64.pyd)
```
But reinstalling vsdpir after that did solve the problem.
Thanks.
