### ISSUE TITLE
ImportError: cannot import name 'ccfDisableAutoLoading' from 'vapoursynth'

### ISSUE THREAD

**Issue by AIisCool** [HolyWu/vs-dpir#44]
```
C:\WINDOWS\system32>python -m vsdpir
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "C:\Program Files\Python312\Lib\site-packages\vsdpir\__init__.py", line 12, in <module>
    from vstools import check_variable, fallback, vs
  File "C:\Program Files\Python312\Lib\site-packages\vstools\__init__.py", line 5, in <module>
    from .utils import *  # noqa: F401, F403
    ^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\vstools\utils\__init__.py", line 1, in <module>
    from . import vs_proxy as vapoursynth
  File "C:\Program Files\Python312\Lib\site-packages\vstools\utils\vs_proxy.py", line 17, in <module>
    from vapoursynth import (
ImportError: cannot import name 'ccfDisableAutoLoading' from 'vapoursynth' (C:\Program Files\Python312\Lib\site-packages\vapoursynth.cp312-win_amd64.pyd)
```

**Comment by AIisCool** [comment]
Ah my apologies, I saw it was addressed here https://github.com/HolyWu/vs-dpir/issues/41

However even reinstalling vsdpir hasn't changed the error

**Comment by AIisCool** [comment]
Ah managed to get it to work now.

**Comment by efschu** [comment]
Would you share, what you did to get it work? I have the same issue._
